# version: '3.8'
# services:
#   laravel:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www/wgbackup
#     networks:
#       - laravel-net

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - .:/var/www/wgbackup
#     networks:
#       - laravel-net

# networks:
#   laravel-net:
#     driver: bridge

###################################
version: '3.8'

services:
  # Database Service
  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gis
      MYSQL_USER: rootnow
      MYSQL_PASSWORD: rootnow
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  # Laravel Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travellist-app
    restart: unless-stopped
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:U8OXvc1VRoZ8ERDRjJBP+Rdlk7P0xSZyFw5swbc38/A=
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      LOG_CHANNEL: daily
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gis
      DB_USERNAME: rootnow
      DB_PASSWORD: rootnow
    volumes:
      - ./:/var/www
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: wgbackup
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app

volumes:
  dbdata:

