version: "3.8"

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/laraveldocker
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql # Menggunakan nama service MySQL sebagai DB_HOST
      - DB_PORT=3306
      - DB_DATABASE=gis
      - DB_USERNAME=rootnow
      - DB_PASSWORD=rootnow

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gis
      MYSQL_USER: rootnow
      MYSQL_PASSWORD: rootnow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
  driver: local