version: '3.8'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
